### ISSUE TITLE
钉钉闪退

### ISSUE THREAD

**Issue by haipengzhou** [flydoos/DingTalkRevokeMsgPatcher#1]
安装之后，测试撤回 钉钉闪退

**Comment by flydoos** [comment]
> 安装之后，测试撤回 钉钉闪退

有没有更详细的说明？这样一句话，没法整，QQ群：223541319，进群找群主远程看看

**Comment by flydoos** [comment]
钉钉安装之后，如果后面有自动更新，就会导致目录会有2个版本钉钉，估计破解的是A那个程序，你使用的却是B程序
D:\Program Files\DingDing\main\current_new
D:\Program Files\DingDing\main\current
他会有这2个版本，如果你选错了，就会有问题
解决方法：把这2个目录下的程序，全都打一次补丁即可
