### ISSUE TITLE
7.0.0-Release.12299103无法使用消息永不已读功能

### ISSUE THREAD

**Issue by zhuzixuan2019241** [flydoos/DingTalkRevokeMsgPatcher#11]
7.0.0-Release.12299103无法使用消息永不已读功能，安装时若勾选，则显示安装失败，还原备份和重装钉钉均无效。若不勾选则正常。杀毒软件全部未在运行

**Comment by flydoos** [comment]
5.1.0版本已经修复此问题，请更新程序即可
