### ISSUE TITLE
[功能请求]加入文件防撤回

### ISSUE THREAD

**Issue by zhuzixuan2019241** [flydoos/DingTalkRevokeMsgPatcher#12]
对于文件防撤回的功能有需求。我设想的实现方法是把收到的文件自动缓存到本地以达到防撤回的效果，文件类型和大小可以自定义（如10Mb以内）。作为可选功能开启，缓存路径也可以自定义
请问有机会加入此功能吗？

**Comment by flydoos** [comment]
暂时没有这个计划
