### ISSUE TITLE
工具读出来的钉钉版本和钉钉显示的不一致。

### ISSUE THREAD

**Issue by Ruling95** [flydoos/DingTalkRevokeMsgPatcher#16]
这是钉钉显示的
![image](https://user-images.githubusercontent.com/49261119/225281381-af8ada8c-04cb-4947-887f-6bc97cd30daa.png)
这是工具读出来的。
![image](https://user-images.githubusercontent.com/49261119/225281417-3c2f231e-d5f3-4d1a-8072-e8945892e58a.png)

钉钉版本是在这个页面下载的
https://www.wuleba.com/1557.html

**Comment by flydoos** [comment]
> 

5.3.2版本的补丁才支持上面这个版本
