### ISSUE TITLE
7.0.20.41407 版本不支持

### ISSUE THREAD

**Issue by AlphaXu917** [flydoos/DingTalkRevokeMsgPatcher#17]

**Comment by flydoos** [comment]
反馈版本不支持的问题，请提供2个东西：
1、补丁左上角的版本号
2、钉钉关于界面的版本号

**Comment by flydoos** [comment]
> 已安装老版本的钉钉，可以使用

因为钉钉很坑，采用灰度发布的机制，每个人看到的最新版本都是不一样的。如果你不给我完整的版本号，我就没办法下载对应的版本测试，如果你还有那个版本的安装包，告诉我“钉钉完整版本号”（未提供），以及补丁运行之后左上角的版本号（已提供）~~不然我只能无视这个版本了

**Comment by index7559** [comment]
此版本不支持




下雨天
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "flydoos/DingTalkRevokeMsgPatcher"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月4日(星期二) 下午5:45
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [flydoos/DingTalkRevokeMsgPatcher] 7.0.20.41407 版本不支持 (Issue #17)





  
已安装老版本的钉钉，可以使用
  
因为钉钉很坑，采用灰度发布的机制，每个人看到的最新版本都是不一样的。如果你不给我完整的版本号，我就没办法下载对应的版本测试，如果你还有那个版本的安装包，告诉我“钉钉完整版本号”（未提供），以及补丁运行之后左上角的版本号（已提供）~~不然我只能无视这个版本了
