### ISSUE TITLE
7.0.20-4049113版本不支持

### ISSUE THREAD

**Issue by ririliu** [flydoos/DingTalkRevokeMsgPatcher#18]
钉钉关于页面版本号：7.0.20-Release.4049113
补丁显示的当前版本：7.0.20.51417

**Comment by flydoos** [comment]
更新至 5.4.1，支持钉钉 7.0.20-Release.4039104、7.0.20-Release.4049113

**Comment by ririliu** [comment]
5.4.1运行报错
![Snipaste_2023-04-10_10-56-58](https://user-images.githubusercontent.com/30514728/230816598-17aef54e-c62b-4219-9dc9-7934aed0d1e7.png)
