### ISSUE TITLE
exe管理员运行报错 

### ISSUE THREAD

**Issue by wangyuan0217** [flydoos/DingTalkRevokeMsgPatcher#19]
![image](https://user-images.githubusercontent.com/12730214/230833760-93358a7c-123b-4bd6-9ed3-0b047daf08f2.png)
![image](https://user-images.githubusercontent.com/12730214/230833816-bf1a9df3-5535-4c9f-9b21-4b0caf28e565.png)

**Comment by flydoos** [comment]
打包有问题导致，已经重新上传压缩包，你重新下载试试
