### ISSUE TITLE
路径问题

### ISSUE THREAD

**Issue by WilderHuang** [flydoos/DingTalkRevokeMsgPatcher#2]
麻烦请教一下，谢谢。
需要选择安装路径"DingTalk.exe"，但是我的钉钉中没有这个文件。
![image](https://user-images.githubusercontent.com/38951166/144192564-d3a77088-35ca-4477-9f57-fe59551bef36.png)
钉钉版本：6.3.5-Release.11308701
![image](https://user-images.githubusercontent.com/38951166/144192730-27e2ef57-a007-4c0b-9538-5ed75c2d1f0d.png)

**Comment by WilderHuang** [comment]
路径选错了 。。。

**Comment by flydoos** [comment]
钉钉安装之后，如果后面有自动更新，就会导致目录会有2个版本钉钉，估计破解的是A那个程序，你使用的却是B程序
D:\Program Files\DingDing\main\current_new
D:\Program Files\DingDing\main\current
他会有这2个版本，如果你选错了，就会有问题
解决方法：把这2个目录下的程序，全都打一次补丁即可

**Comment by WilderHuang** [comment]
好的，感谢，非常好用，牛逼！！！
