### ISSUE TITLE
7.0.20-Release.4119105版本不支持

### ISSUE THREAD

**Issue by ririliu** [flydoos/DingTalkRevokeMsgPatcher#20]
钉钉又自动静默更新了。。。
钉钉关于页面版本号：7.0.20-Release.4119105
补丁显示的当前版本：7.0.20.55873

**Comment by flydoos** [comment]
> 钉钉又自动静默更新了。。。 钉钉关于页面版本号：7.0.20-Release.4119105 补丁显示的当前版本：7.0.20.55873

感谢提醒，更新至 5.4.2，支持钉钉 7.0.20-Release.4119105、7.0.20-Release.4129103
