### ISSUE TITLE
专属钉钉开启了聊天窗粘贴功能控制导致无法粘贴

### ISSUE THREAD

**Issue by lidapao92** [flydoos/DingTalkRevokeMsgPatcher#23]
您好，专属钉钉管理员开启了聊天窗粘贴功能控制，导致在其他组织无法粘贴。能做features吗？

https://m.dingtalk.com/qidian/help-detail-1060886219

**Comment by flydoos** [comment]
我没有专属版钉钉，爱莫能助~~
