### ISSUE TITLE
7.0.40-Release.6289101 Native  大佬，這個版本暂时还不支持嘛。

### ISSUE THREAD

**Issue by Ruling95** [flydoos/DingTalkRevokeMsgPatcher#24]
![image](https://github.com/flydoos/DingTalkRevokeMsgPatcher/assets/49261119/63d67e85-b309-4bbd-821c-812dc6865e10)

坐等支持这個版本

工具版本：
DingTalkRevokeMsgPatcher.v5.7.2

**Comment by Ruling95** [comment]
![image](https://github.com/flydoos/DingTalkRevokeMsgPatcher/assets/49261119/5a3c5e7b-373e-408d-a1fb-1b35f8a1d9ed)

**Comment by flydoos** [comment]
> ![image](https://user-images.githubusercontent.com/49261119/250037927-63d67e85-b309-4bbd-821c-812dc6865e10.png)
> 
> 坐等支持这個版本
> 
> 工具版本： DingTalkRevokeMsgPatcher.v5.7.2

感谢反馈，今天中午已经在着手研究了，刚刚已经发布5.8.0版本，已经支持 7.0.40-Release.6289101
