### ISSUE TITLE
安装补丁后，打开聊天记录一片空白

### ISSUE THREAD

**Issue by sanchez0623** [flydoos/DingTalkRevokeMsgPatcher#25]
好像没人出现跟我一样的状况，请问这个要怎么解决？？
![微信截图_20230705094926](https://github.com/flydoos/DingTalkRevokeMsgPatcher/assets/45893054/6d5b7150-d6db-410c-bfcc-70ce94938c9b)

**Comment by flydoos** [comment]
吾乐吧那边，前几天回复过一次了：这个是你的本地文件损坏了，重装钉钉，然后重新使用补丁才可以解决。一般是因为使用补丁的时候，因为某些原因程序被终止导致的~~重装钉钉，再打一次补丁吧
