### ISSUE TITLE
7.0.55-Release.8159101 大佬来个适配嘛

### ISSUE THREAD

**Issue by Ruling95** [flydoos/DingTalkRevokeMsgPatcher#28]
![image](https://github.com/flydoos/DingTalkRevokeMsgPatcher/assets/49261119/524a1179-5388-401a-9911-b1ad1c1c8f14)
大佬，這個版本有考虑搞不。

**Comment by flydoos** [comment]
> ![image](https://user-images.githubusercontent.com/49261119/267826537-524a1179-5388-401a-9911-b1ad1c1c8f14.png) 大佬，這個版本有考虑搞不。

这个是个人版？还是企业版？

**Comment by flydoos** [comment]
你这个是个人版的吧，目前并不想做个人版：
1、现在个人版只是内测，并没有正式发布
2、钉钉安装包大概480MB，每次都要卸载旧版本，安装新版，我的网络限速400K/S，太费时间了
3、我自己只用企业版

如果要支持你这个版本，我只能“盲写代码”（也就是按照企业版的补丁，直接适配个人版，但是我自己不去测试了，因为不想安装个人版，然后又重装回去企业版），你可以用补丁打开你的钉钉，截图看看左侧的版本号是什么？

我需要知道【补丁左侧的版本号 + 钉钉关于的版本号】，然后可以按照最新“企业版”钉钉盲写代码，你可以加Q群390669197，帮我内测，没问题再发布出来

**Comment by Ruling95** [comment]
晚点我看看先。现在要搞别的事。

**Comment by Ruling95** [comment]
![image](https://github.com/flydoos/DingTalkRevokeMsgPatcher/assets/49261119/a3806166-cdaa-40d3-9c82-134105a4688f)
最新工具打开是這样的。
我這版本，2合一版本，可以随时切换到个人版本也可以随时切换到标准版本的那种。
切到个人版本就功能类似notion带AI的。
切到标准版本就是正常的公司内部沟通啥的。

**Comment by flydoos** [comment]
更新至 5.9.5，支持钉钉 7.0.55-Release.8159101（未亲测，盲写代码）、7.1.0-Release.9159115（已亲测）
