### ISSUE TITLE
高DPI适配问题

### ISSUE THREAD

**Issue by Return761** [flydoos/DingTalkRevokeMsgPatcher#29]
最新版本（截至5.9.7）仍然不能正常适配高DPI，若在属性中将DPI处理模式改为“应用程序”程序主页面大部分会缩小而不是被缩放到正确大小，然而插件的区域却能正常缩放

**Comment by flydoos** [comment]
后面研究一下

**Comment by flydoos** [comment]
![20231115173204](https://github.com/flydoos/DingTalkRevokeMsgPatcher/assets/3932827/0c803b5c-8f3e-4057-b702-45fadf663c8e)
我刚刚试了下，没发现你说的问题啊，全部都是整体缩放的。没看懂你的具体需求是什么？

**Comment by Return761** [comment]
> ![20231115173204](https://user-images.githubusercontent.com/3932827/283070484-0c803b5c-8f3e-4057-b702-45fadf663c8e.jpg)我刚刚试了下，没发现你说的问题啊，全部都是整体缩放的。没看懂你的具体需求是什么？

仔细看最后面的标题栏字体和底下界面字的区别，字是虚的，是界面根本就没有进行缩放，系统直接把100%的界面放大的，如果在应用程序属性里把高DPI适配模式改为“应用程序”，则系统不进行放大，会发现150%和100%是一样大的
(这张图是150%下的状况）
<img width="1052" alt="Snipaste_2023-11-17_19-32-49" src="https://github.com/flydoos/DingTalkRevokeMsgPatcher/assets/113340011/dbdf65a1-fda8-4121-bca5-c62ddb49e61d">

**Comment by flydoos** [comment]
最近测试过了，没有找到说的“应用程序”，但是可以看到“DPI”选项，全部试过了，效果跟上面截图完全一致，字体是虚的，暂时无法适配
