### ISSUE TITLE
xxx (2023-11-27 10:03:27) 撤回的消息为: 该消息被撤回 重新编辑

### ISSUE THREAD

**Issue by faintout** [flydoos/DingTalkRevokeMsgPatcher#30]
提示 该消息被撤回 

钉钉版本：7.1.0-Release.10099103

**Comment by flydoos** [comment]
历史的车轮是向前进的，你发的这个是“老版本”，一般不会调整，你可以下载最新版：
更新至 5.9.10，支持钉钉 7.1.10-Release.11169101
