### ISSUE TITLE
5.10.1 无法发起会议和修改状态

### ISSUE THREAD

**Issue by zimo1213** [flydoos/DingTalkRevokeMsgPatcher#32]
您好，新版本发起会议后不能进入会议 
钉钉版本7.1.10-Release.11169101、7.1.10-Release.11229101  换了两台window都能复现

**Comment by flydoos** [comment]
> 您好，新版本发起会议后不能进入会议 钉钉版本7.1.10-Release.11169101、7.1.10-Release.11229101 换了两台window都能复现

确定是打补丁之后，才不行？不打补丁可以进入会议室吗？

**Comment by zimo1213** [comment]
> > 您好，新版本发起会议后不能进入会议 钉钉版本7.1.10-Release.11169101、7.1.10-Release.11229101 换了两台window都能复现
> 
> 确定是打补丁之后，才不行？不打补丁可以进入会议室吗？

是的，目前卸载钉钉勾选删除个人配置，重装钉钉后就可以发起会议并加入会议中
然后又打了补丁后又不行了

**Comment by flydoos** [comment]
已核实，7.1.10-Release.11229101 确实无法“进入会议”，但是最近较忙，这个问题短期内没有修复计划。
建议你使用手机钉钉加入会议，或者暂时不使用此补丁
PS：如果以后修复了此问题，会在这里回复你

**Comment by zimo1213** [comment]
好的好的，感谢
