### ISSUE TITLE
表情快捷回复消息，未成功设置已读

### ISSUE THREAD

**Issue by will961123** [flydoos/DingTalkRevokeMsgPatcher#33]
悬浮消息上，使用快捷表情回复别人后，对方还是显示未读状态

![image](https://github.com/flydoos/DingTalkRevokeMsgPatcher/assets/45943678/5b89b48f-4131-45dc-a79c-9649d9fa9d0f)

**Comment by flydoos** [comment]
这个是已知问题，无法解决，因为钉钉认为表情回复，不是消息回复，所以不会触发接收消息事件。所以不想暴露，老老实实发送文字消息回复
