### ISSUE TITLE
当前版本：7.1.0.1019 不支持启动撤回

### ISSUE THREAD

**Issue by sanchez0623** [flydoos/DingTalkRevokeMsgPatcher#34]
![image](https://github.com/flydoos/DingTalkRevokeMsgPatcher/assets/45893054/19492e21-8d20-4a66-89c3-4c646c45e4a1)

你好，大佬。
麻烦看下这个问题

**Comment by flydoos** [comment]
你需要提供钉钉的关于界面版本号截图（未提供），以及上面这个截图版本号才行（已提供），我才可以下载对应版本分析~~你也可以下载吾乐吧支持的版本再使用这个补丁

**Comment by flydoos** [comment]
更新至 5.11.0，支持钉钉 7.5.0-Release.13049105、7.5.0-Release.13039104、7.1.10-Release.12089105
请下载最新版本
