### ISSUE TITLE
钉钉多开快捷方式无法使用

### ISSUE THREAD

**Issue by redleafnew** [flydoos/DingTalkRevokeMsgPatcher#35]
双击时提示这个是怎么回事啊？
D:\DingDing\main\current
和D:\DingDing\main\current_new两个目录都应用补丁了。
Win 11操作系统

![image](https://github.com/flydoos/DingTalkRevokeMsgPatcher/assets/22135631/219bfd38-9b7b-4708-9081-a797137c4af3)

![image](https://github.com/flydoos/DingTalkRevokeMsgPatcher/assets/22135631/63f31c1f-5705-4e1f-afbe-1c5fbfe61cc6)

**Comment by flydoos** [comment]
本程序要解压之后才能用，并且要杀软添加信任，负责会被误杀，还有问题的话根据“readme”添加QQ群咨询
