### ISSUE TITLE
读取撤回消息失败

### ISSUE THREAD

**Issue by IM-Boting** [flydoos/DingTalkRevokeMsgPatcher#36]
![image](https://github.com/flydoos/DingTalkRevokeMsgPatcher/assets/47098029/e917d823-eda8-459e-af9f-b05219f32923)

> 钉钉版本号：7.5.0-Release.13049105

**Comment by flydoos** [comment]
能出现这个，就表示正常。提示失败，只是不属于该类型的消息。这个补丁主要是解决“文字消息，图片消息”

**Comment by IM-Boting** [comment]
> 个补丁主要是解决“文字消息，图片消息”

我这就是截图，截取的屏幕发送，然后撤回。目前是只支持图片文件类型的消息吗？拍的照片撤回后可见。

**Comment by flydoos** [comment]
> > 个补丁主要是解决“文字消息，图片消息”
> 
> 我这就是截图，截取的屏幕发送，然后撤回。目前是只支持图片文件类型的消息吗？拍的照片撤回后可见。

图片可以的，但是要别人发给你的，才能防撤回。。。自己发的不行，但是，如果你用手机发给自己，然后手机撤回，PC端也可以防撤回
