### ISSUE TITLE
佬，有做飞书防撤回的计划吗

### ISSUE THREAD

**Issue by VAabcjjsw** [flydoos/DingTalkRevokeMsgPatcher#38]

**Comment by flydoos** [comment]
去年研究过，但是飞书120秒之后，还是会把消息强制销毁，这就意味着，需要自己把数据保存起来，然后才能用于后期展示，但是一个补丁还要去保存数据就有点扯，除此之外，还有不少其他技术难题要突破，我自己没有飞书需求，应该是不会折腾了

**Comment by qiuyueovo** [comment]
我感觉还是·可以研究一下的。现在很多人也有飞书的需求。

**Comment by flydoos** [comment]
https://github.com/flydoos/FeiShuRevokeMsgPatcher

你要的飞书，发布了![mmexport1711716180768.png](https://github.com/flydoos/DingTalkRevokeMsgPatcher/assets/3932827/94dc2012-64e1-4988-a80e-621a61a2df68)

**Comment by flydoos** [comment]
> 我感觉还是·可以研究一下的。现在很多人也有飞书的需求。

已发布，目前仅支持飞书文字消息防撤回，更多功能期待以后完善

**Comment by qiuyueovo** [comment]
> > 我感觉还是·可以研究一下的。现在很多人也有飞书的需求。
> 
> 已发布，目前仅支持飞书文字消息防撤回，更多功能期待以后完善

佬，牛逼
