### ISSUE TITLE
安全提示

### ISSUE THREAD

**Issue by ljili2003** [flydoos/DingTalkRevokeMsgPatcher#39]
![image](https://github.com/flydoos/DingTalkRevokeMsgPatcher/assets/79502189/5b83cf2d-846e-4077-b348-815d7f349561)
![image](https://github.com/flydoos/DingTalkRevokeMsgPatcher/assets/79502189/38a7308d-de37-4ed9-9d5d-29bcf13ddc4e)

**Comment by flydoos** [comment]
感谢反馈，你是第一个反馈此问题的，3月21号也陆续收到几位用户反馈次问题。经过测试发现，**如果你使用钉钉官方自带的“开机启动”或者官方的“桌面快捷方式”启动钉钉，就会出现这个安全提示。建议你取消官方的开机启动，然后每次使用补丁生成的“钉钉多开.lnk”桌面快捷方式启动，用这个启动就不会有安全提醒。**
