### ISSUE TITLE
7.5.2版本不支持哦

### ISSUE THREAD

**Issue by Marhoosh** [flydoos/DingTalkRevokeMsgPatcher#41]
![image](https://github.com/flydoos/DingTalkRevokeMsgPatcher/assets/54924700/875786c8-61aa-40b4-aa89-a7d682895e15)

**Comment by flydoos** [comment]
钉钉采用的是“灰度发布”机制，所以，每个人看到的“最新版”都不是真正的最新版，建议大家进Q群：390669197 反馈最新版本，作者有空的话会进行升级。

反馈最新版本，需要提供2个截图：
1、钉钉关于界面的版本号截图
2、补丁主界面上的版本号截图

但是，补丁现在最新支持的版本是“7.5.13-Release.41510801”，也就是支持 7.5.13 版本，你上面的反馈的是 7.5.2 属于老版本，一旦补丁支持了新版本，是不会再支持老版本的~~ 赶紧去吾乐吧软件站升级 官方最新版钉钉：https://www.wuleba.com/?p=1557
