### ISSUE TITLE
引用的图片无法进行查看BUG

### ISSUE THREAD

**Issue by uu-xixi** [flydoos/DingTalkRevokeMsgPatcher#48]
版本号：7.6.0-Release.72310802 Native
对方发来的消息中包含引用的图片，无法双击查看照片。
![image](https://github.com/user-attachments/assets/65fb5365-5abb-4ccb-9ff4-e94f995d3b45)

**Comment by flydoos** [comment]
![20240729145820](https://github.com/user-attachments/assets/b816a6e7-0a53-46e0-9125-58569d28d6f1)
已亲测，没有这个问题
如果你使用的是最新版的 6.3.3 版本补丁，则不会有这个问题
因为这个问题已经在 6.3.2 的时候修复了
建议你升级最新版补丁，并且删除以前的旧补丁，我怀疑你的桌面“钉钉多开”快捷方式，使用的依然是旧版本补丁导致，你把快捷方式重新生成一下

**Comment by uu-xixi** [comment]
> [![20240729145820](https://private-user-images.githubusercontent.com/3932827/352945091-b816a6e7-0a53-46e0-9125-58569d28d6f1.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIyMzcwMjgsIm5iZiI6MTcyMjIzNjcyOCwicGF0aCI6Ii8zOTMyODI3LzM1Mjk0NTA5MS1iODE2YTZlNy0wYTUzLTQ2ZTAtOTEyNS01ODU2OWQyOGQ2ZjEuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MjlUMDcwNTI4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9M2Q5OTU2MDZmZjc2NjUxZDZkNTdjMDQwZmIyNzRlNDQzNjg2Yzc0Y2NhOTAzZDQzZDlkYWQ5ODkzOTVjYWNmMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Y8lS9gzjPGujyRgsHgeB1LN5mu_Dvg61WBl8Zhcf3Zs)](javascript:void(0)) 已亲测，没有这个问题 如果你使用的是最新版本的6.3.3版本补丁，则不会有这个问题 因为这个问题已经在6.3.2的时候修复了 建议你升级最新版本补丁，并且删除以前的旧版本，我怀疑你的桌面“钉钉多开”快捷方式，使用的依然是旧版本补丁导致，你把快捷方式重新生成一下

感谢，升级最新版本补丁已解决问题。 但是钉钉进行了风险提示

> 【风险提示】系统检测到您当前使用Windows版钉钉非官方客户端，请到钉钉官网( https://www.dingtalk.com/download#/ )下载客户端重新安装。请勿使用钉钉外挂及非官方客户端，继续使用可能影响钉钉账号正常登录。

**Comment by flydoos** [comment]
> > ![20240729145820](https://private-user-images.githubusercontent.com/3932827/352945091-b816a6e7-0a53-46e0-9125-58569d28d6f1.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIyMzcwMjgsIm5iZiI6MTcyMjIzNjcyOCwicGF0aCI6Ii8zOTMyODI3LzM1Mjk0NTA5MS1iODE2YTZlNy0wYTUzLTQ2ZTAtOTEyNS01ODU2OWQyOGQ2ZjEuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MjlUMDcwNTI4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9M2Q5OTU2MDZmZjc2NjUxZDZkNTdjMDQwZmIyNzRlNDQzNjg2Yzc0Y2NhOTAzZDQzZDlkYWQ5ODkzOTVjYWNmMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Y8lS9gzjPGujyRgsHgeB1LN5mu_Dvg61WBl8Zhcf3Zs) 已亲测，没有这个问题 如果你使用的是最新版本的6.3.3版本补丁，则不会有这个问题 因为这个问题已经在6.3.2的时候修复了 建议你升级最新版本补丁，并且删除以前的旧版本，我怀疑你的桌面“钉钉多开”快捷方式，使用的依然是旧版本补丁导致，你把快捷方式重新生成一下
> 
> 感谢，升级最新版本补丁已解决问题。 但是钉钉进行了风险提示
> 
> > 【风险提示】系统检测到您当前使用Windows版钉钉非官方客户端，请到钉钉官网( https://www.dingtalk.com/download#/ )下载客户端重新安装。请勿使用钉钉外挂及非官方客户端，继续使用可能影响钉钉账号正常登录。

这个问题，小编已经无能为力了，需要懂DLL HOOK的大神来支援才能处理，具体原因看这里，字体加粗部分：https://github.com/flydoos/DingTalkRevokeMsgPatcher/releases/tag/6.3.3

**Comment by uu-xixi** [comment]
> > > [![20240729145820](https://private-user-images.githubusercontent.com/3932827/352945091-b816a6e7-0a53-46e0-9125-58569d28d6f1.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIyMzcwMjgsIm5iZiI6MTcyMjIzNjcyOCwicGF0aCI6Ii8zOTMyODI3LzM1Mjk0NTA5MS1iODE2YTZlNy0wYTUzLTQ2ZTAtOTEyNS01ODU2OWQyOGQ2ZjEuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MjlUMDcwNTI4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9M2Q5OTU2MDZmZjc2NjUxZDZkNTdjMDQwZmIyNzRlNDQzNjg2Yzc0Y2NhOTAzZDQzZDlkYWQ5ODkzOTVjYWNmMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Y8lS9gzjPGujyRgsHgeB1LN5mu_Dvg61WBl8Zhcf3Zs)](javascript:void(0)) 已亲测，没有这个问题 如果你使用的是最新版本的6.3.3版本补丁，则不会有这个问题 因为这个问题已经在6.3.2的时候修复了 建议你升级最新版本补丁，并且删除以前的旧版本，我怀疑你的桌面“钉钉多开”快捷方式，使用的依然是旧版本补丁导致，你把快捷方式重新生成一下
> > 
> > 
> > 感谢，升级最新版本补丁已解决问题。 但是钉钉进行了风险提示
> > > 【风险提示】系统检测到您当前使用Windows版钉钉非官方客户端，请到钉钉官网( https://www.dingtalk.com/download#/ )下载客户端重新安装。请勿使用钉钉外挂及非官方客户端，继续使用可能影响钉钉账号正常登录。
> 
> 这个问题，小编已经无能为力了，需要懂DLL HOOK的大神来支援才能处理，具体原因看这里，字体加粗部分：https://github.com/flydoos/DingTalkRevokeMsgPatcher/releases/tag/6.3.3

感谢大佬提供这么优秀的开源项目，鞠躬！
