### ISSUE TITLE
截图发出的图片撤回后没有显示出来

### ISSUE THREAD

**Issue by hqbin** [flydoos/DingTalkRevokeMsgPatcher#49]
只显示：撤回的图片为: 35CF9EDE-062A-4592-8C85-8B94D6BD15B2.png

**Comment by flydoos** [comment]
>  只显示：撤回的图片为: 35CF9EDE-062A-4592-8C85-8B94D6BD15B2.png

别人发的才可以看到，你自己发自己撤回就是这样显示……当然，如果你用手机发图，手机撤回，电脑也可以正常显示

**Comment by hqbin** [comment]
别人发出来的图片也是看不见
![369DD0BC-5F13-44d5-81B5-E8A5085648E6](https://github.com/user-attachments/assets/45460fad-5461-40cb-a2c6-1adab7c2f9c1)

**Comment by hqbin** [comment]
别人撤回的图片也会看不见
![44E5BDED-3A3C-41c8-904A-F1FCE13ACAB1](https://github.com/user-attachments/assets/9886b34e-0d1d-4237-bf8b-a7471e7d40fe)

**Comment by hqbin** [comment]
> > 只显示：撤回的图片为: 35CF9EDE-062A-4592-8C85-8B94D6BD15B2.png
> 
> 别人发的才可以看到，你自己发自己撤回就是这样显示……当然，如果你用手机发图，手机撤回，电脑也可以正常显示

**Comment by flydoos** [comment]
> 别人撤回的图片也会看不见
> ![44E5BDED-3A3C-41c8-904A-F1FCE13ACAB1](https://github.com/user-attachments/assets/9886b34e-0d1d-4237-bf8b-a7471e7d40fe)
> 

你这是“表情”，不是图片，不分表情无法显示的，具体哪些我也不知道，图片是肯定可以的
