### ISSUE TITLE
钉钉6.5.0 3249116不支持补丁

### ISSUE THREAD

**Issue by ing123baby** [flydoos/DingTalkRevokeMsgPatcher#5]
![QQ图片20220325111146](https://user-images.githubusercontent.com/75151010/160047184-0e5ec54d-038c-49e8-871a-28973b1a83d0.png)

**Comment by flydoos** [comment]
感谢提醒，刚刚已经更新，请下载最新版
钉钉防撤回吾乐吧优化版 2022-03-25（6.5.0-Release.3249116）
