### ISSUE TITLE
无法成功完成操作因为包含

### ISSUE THREAD

**Issue by godonlyknew** [flydoos/DingTalkRevokeMsgPatcher#52]
这个可以跳过吗？ 点击exe的时候 会提示 无法成功完成操作，因为文件包含病毒或潜在的垃圾软件

**Comment by flydoos** [comment]
看不懂在说啥

**Comment by godonlyknew** [comment]
启动exe文件的时候 提示：因为文件包含病毒或潜在的垃圾软件的......... 这样的信息
