### ISSUE TITLE
为啥6.3.35.53373 不支持

### ISSUE THREAD

**Issue by tanaer** [flydoos/DingTalkRevokeMsgPatcher#6]
烦请作者解惑，感谢

![image](https://user-images.githubusercontent.com/3828685/161199597-87759478-feff-4ff4-b17f-516a9e8f944b.png)

![image](https://user-images.githubusercontent.com/3828685/161199667-a445c717-c06f-479d-ac75-f503eaa2299d.png)

**Comment by flydoos** [comment]
首先，我这边没见过6.3.35版本，目前最新是6.5.0（上个版本是6.3.25）
找不到你说的这个版本，建议加群（Readme有写），提供安装包给我（因为钉钉是部分用户推送新版的，所以拿不到最新版也很正常）

钉钉官方历史版本（PC版） https://www.wuleba.com/1557.html
钉钉消息防撤回补丁（最新版） https://www.wuleba.com/47.html
